import type { Metadata } from "next";
import "./globals.css";
import SideNavServer from "@/components/SideNav/SideNavServer";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Content Publishing Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-500/10 h-dvh 2xl:max-w-[1280px] mx-auto">
        <Providers>
          <div className="flex flex-col md:flex-row md:overflow-hidden h-full">
            <div className="w-full flex-none md:w-64">
              <SideNavServer />
            </div>
            <div className="grow p-4 text-gray-500 overflow-y-auto">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
