import type { Metadata } from "next";
import "./globals.css";
import SideNavServer from "@/components/SideNav/SideNavServer";

export const metadata: Metadata = {
  title: "Content Publishing Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col md:flex-row md:overflow-hidden bg-gray-500/10 h-screen max-md:h-auto">
          <div className="w-full flex-none md:w-64">
            <SideNavServer />
          </div>
          <div className="grow p-4 text-gray-500">{children}</div>
        </div>
      </body>
    </html>
  );
}
